#ifndef USER_SETTINGS_H
#define USER_SETTINGS_H

#define WOLFSSL_USER_SETTINGS
#define NO_WOLFSSL_DIR
#define WOLFSSL_AES_DIRECT
#define SINGLE_THREADED
#define HAVE_PK_CALLBACKS
#define WOLFSSL_USER_IO
#define NO_WRITEV
#define TIME_T_NOT_64BIT
#define NO_FILESYSTEM
#define NO_DEV_RANDOM
#define WC_NO_DEFAULT_DEVID
#define WOLF_CRYPTO_CB

#endif /* USER_SETTINGS_H */
