use std::{env, fs, io::Write, path::Path, path::PathBuf};

use base64::{Engine, engine::general_purpose::STANDARD as B64};
use ed25519_dalek::{SigningKey, hazmat::ExpandedSecretKey};
use hkdf::Hkdf;
use pbkdf2::pbkdf2_hmac;
use rand::RngCore;
use sha2::Sha256;
use x25519_dalek::{PublicKey, StaticSecret};

// ─── Permission parsing ────────────────────────────────────────────

struct Perm {
    group_id: u16,
    read: bool,
    write: bool,
    receive: bool,
}

fn parse_permissions(s: &str) -> Vec<Perm> {
    s.split(':')
        .map(|tok| {
            let (hex_id, flags) = tok
                .split_once('=')
                .expect("permission format: HEX_GROUP_ID=RWC");
            let b = flags.as_bytes();
            Perm {
                group_id: u16::from_str_radix(hex_id.trim(), 16).expect("group_id must be hex u16"),
                read: b.first().copied() == Some(b'R'),
                write: b.get(1).copied() == Some(b'W'),
                receive: b.get(2).copied() == Some(b'C'),
            }
        })
        .collect()
}

// ─── HSM static secret ────────────────────────────────────────────

/// Cached in OUT_DIR so incremental rebuilds keep the same key.
/// A `cargo clean` or new target dir triggers fresh generation.
fn load_or_generate_secret() -> StaticSecret {
    let path: PathBuf = Path::new(&env::var("OUT_DIR").unwrap()).join(".hsm_secret");

    if path.exists() {
        let bytes = fs::read(&path).expect("failed to read cached HSM secret");
        let arr: [u8; 32] = bytes.try_into().expect("cached HSM secret is not 32 bytes");
        return StaticSecret::from(arr);
    }

    let mut secret_bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut secret_bytes);
    fs::write(&path, secret_bytes).expect("failed to persist HSM secret");

    StaticSecret::from(secret_bytes)
}

// ─── Cryptographic helpers ─────────────────────────────────────────

fn hash_pin(pin: &str) -> ([u8; 32], [u8; 16]) {
    let mut salt = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut salt);
    let mut key = [0u8; 32];
    pbkdf2_hmac::<Sha256>(pin.as_bytes(), &salt, 5, &mut key);
    (key, salt)
}

fn derive_aes_key(hsm_secret: &StaticSecret, peer_pub: &[u8; 32]) -> [u8; 16] {
    let shared = hsm_secret.diffie_hellman(&PublicKey::from(*peer_pub));
    let hk = Hkdf::<Sha256>::new(None, shared.as_bytes());
    let mut aes = [0u8; 16];
    hk.expand(b"aes-gcm key", &mut aes).expect("HKDF expand");
    aes
}

// ─── Formatting helpers ────────────────────────────────────────────

fn hex_inline(b: &[u8]) -> String {
    let h: Vec<_> = b.iter().map(|x| format!("0x{x:02X}")).collect();
    format!("[{}]", h.join(", "))
}

fn hex_block(b: &[u8], indent: usize) -> String {
    let pad = " ".repeat(indent);
    b.chunks(8)
        .map(|c| {
            let h: Vec<_> = c.iter().map(|x| format!("0x{x:02X}")).collect();
            format!("{pad}{},", h.join(", "))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn b64_key(v: &serde_json::Value) -> [u8; 32] {
    println!("{}", v);
    B64.decode(v.as_str().expect("expected JSON string"))
        .expect("base64 decode")
        .try_into()
        .expect("key must be exactly 32 bytes")
}

// ─── Code generation ───────────────────────────────────────────────

fn main() {
    let secrets_path = env::var("SECRETS_FILE").expect("env SECRETS_FILE required");
    let hsm_pin = env::var("HSM_PIN").expect("env HSM_PIN required");
    let perm_str = env::var("PERMISSIONS").expect("env PERMISSIONS required");

    for var in ["SECRETS_FILE", "HSM_PIN", "PERMISSIONS"] {
        println!("cargo:rerun-if-env-changed={var}");
    }
    println!("cargo:rerun-if-changed={secrets_path}");

    // ── Parse inputs ───────────────────────────────────────────────
    let json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&secrets_path).expect("cannot read SECRETS_FILE"))
            .expect("invalid secrets JSON");

    let key_pairs = json["ecc_key_pairs"]
        .as_object()
        .expect("JSON missing `ecc_key_pairs` object");

    let hsm_secret = load_or_generate_secret();
    let hsm_public = PublicKey::from(&hsm_secret);

    let perms = parse_permissions(&perm_str);
    let (pin_hash, pin_salt) = hash_pin(&hsm_pin);

    // ── Open output file ───────────────────────────────────────────
    let dest: PathBuf =
        Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("src/secrets_generated.rs");

    let mut f = fs::File::create(&dest).expect("cannot create secrets_generated.rs");

    macro_rules! w {
        ()              => { writeln!(f).unwrap() };
        ($($arg:tt)+)   => { writeln!(f, $($arg)+).unwrap() };
    }

    w!("// Auto-generated by build.rs — do not edit by hand");
    w!();
    w!("use crate::permission::{{");
    w!("    EncryptionKeyPair, GroupPermission, ReadKeyPair, ReceiveKeyPair, WriteKeyPair,");
    w!("    SignatureKeyPair,");
    w!("}};");
    w!("use ed25519_dalek::{{SigningKey, VerifyingKey}};");
    w!();

    // ── PIN_HASH / PIN_SALT / HSM_PUBLIC_KEY ───────────────────────
    w!(
        "pub const PIN_HASH: [u8; 32] = [\n{}\n];",
        hex_block(&pin_hash, 4)
    );
    w!();
    w!(
        "pub const PIN_SALT: [u8; 16] = [\n{}\n];",
        hex_block(&pin_salt, 4)
    );
    w!();
    w!("pub const NUM_PERMS: usize = {};", perms.len());
    w!();
    w!(
        "pub const HSM_PUBLIC_KEY: [u8; 32] = [\n{}\n];",
        hex_block(hsm_public.as_bytes(), 4)
    );
    w!();

    // ── PERMISSIONS (const — no keys, just flags) ──────────────────
    w!("pub const PERMISSIONS: [GroupPermission; NUM_PERMS] = [");
    for p in &perms {
        w!("    GroupPermission {{");
        w!("        group_id: {:#06x},", p.group_id);
        w!("        read_perm: {},", p.read);
        w!("        write_perm: {},", p.write);
        w!("        receive_perm: {},", p.receive);
        w!("    }},");
    }
    w!("];");
    w!();

    // ── READ_KEYS (const — EncryptionKeyPair is all byte arrays) ──
    w!("pub const READ_KEYS: [ReadKeyPair; NUM_PERMS] = [");
    for p in &perms {
        let gid_str = p.group_id.to_string();
        let gk = key_pairs
            .get(&gid_str)
            .unwrap_or_else(|| panic!("no keys for group_id {gid_str} in secrets JSON"));

        let read_pub = b64_key(&gk["read"]["public"]);
        let read_aes = derive_aes_key(&hsm_secret, &read_pub);
        let read_priv: Option<[u8; 32]> = p.read.then(|| b64_key(&gk["read"]["private"]));

        w!("    ReadKeyPair {{");
        w!("        group_id: {:#06x},", p.group_id);
        w!("        key_pair: EncryptionKeyPair {{");
        w!("            encrypt_key: {},", hex_inline(&read_aes));
        w!(
            "            decrypt_key: {},",
            hex_inline(&read_priv.unwrap_or([0; 32]))
        );
        w!("        }},");
        w!("    }},");
    }
    w!("];");
    w!();

    // ── RECEIVE_KEYS (const — EncryptionKeyPair is all byte arrays)
    w!("pub const RECEIVE_KEYS: [ReceiveKeyPair; NUM_PERMS] = [");
    for p in &perms {
        let gid_str = p.group_id.to_string();
        let gk = key_pairs
            .get(&gid_str)
            .unwrap_or_else(|| panic!("no keys for group_id {gid_str} in secrets JSON"));

        let recv_pub = b64_key(&gk["receive"]["public"]);
        let recv_aes = derive_aes_key(&hsm_secret, &recv_pub);
        let recv_priv: Option<[u8; 32]> = p.receive.then(|| b64_key(&gk["receive"]["private"]));

        w!("    ReceiveKeyPair {{");
        w!("        group_id: {:#06x},", p.group_id);
        w!("        key_pair: EncryptionKeyPair {{");
        w!("            encrypt_key: {},", hex_inline(&recv_aes));
        w!(
            "            decrypt_key: {},",
            hex_inline(&recv_priv.unwrap_or([0; 32]))
        );
        w!("        }},");
        w!("    }},");
    }
    w!("];");
    w!();

    // ── Raw write key bytes (const) for runtime init ───────────────
    // We store the raw Ed25519 bytes as const so init_write_keys()
    // can construct the dalek types at runtime.
    w!("pub struct RawWriteKeys {{");
    w!("    pub group_id: u16,");
    w!("    pub expanded_scalar: Option<[u8; 32]>,");
    w!("    pub expanded_prefix: Option<[u8; 32]>,");
    w!("    pub verifying_key_bytes: [u8; 32],");
    w!("}}");
    w!();
    w!("pub const RAW_WRITE_KEYS: [RawWriteKeys; NUM_PERMS] = [");
    for p in &perms {
        let gid_str = p.group_id.to_string();
        let gk = key_pairs
            .get(&gid_str)
            .unwrap_or_else(|| panic!("no keys for group_id {gid_str} in secrets JSON"));

        let write_pub = b64_key(&gk["write"]["public"]);
        let write_priv: Option<[u8; 32]> = p.write.then(|| b64_key(&gk["write"]["private"]));

        let (scalar_bytes, hash_prefix_bytes) = match write_priv {
            Some(priv_bytes) => {
                let expanded = ExpandedSecretKey::from(&priv_bytes);
                (Some(expanded.scalar.to_bytes()), Some(expanded.hash_prefix))
            }
            None => (None, None),
        };

        w!("    RawWriteKeys {{");
        w!("        group_id: {:#06x},", p.group_id);
        match (scalar_bytes, hash_prefix_bytes) {
            (Some(scalar), Some(hash_prefix)) => {
                w!("        expanded_scalar: Some({}),", hex_inline(&scalar));
                w!(
                    "        expanded_prefix: Some({}),",
                    hex_inline(&hash_prefix)
                );
            }
            _ => {
                w!("        expanded_scalar: None,");
                w!("        expanded_prefix: None,");
            }
        }

        w!("        verifying_key_bytes: {},", hex_inline(&write_pub));
        w!("    }},");
    }
    w!("];");
    w!();
}
