use std::{env, fs, io::Write, path::Path, path::PathBuf};

use base64::{Engine, engine::general_purpose::STANDARD as B64};
use hkdf::Hkdf;
use pbkdf2::pbkdf2_hmac;
use rand::RngCore;
use sha2::Sha256;
use x25519_dalek::{PublicKey, StaticSecret};

// ─── Permission parsing ────────────────────────────────────────────

struct Perm {
    group_id: u16,
    read: bool,
    write: bool,
    receive: bool,
}

fn parse_permissions(s: &str) -> Vec<Perm> {
    s.split(':')
        .map(|tok| {
            let (hex_id, flags) = tok
                .split_once('=')
                .expect("permission format: HEX_GROUP_ID=RWC");
            let b = flags.as_bytes();
            Perm {
                group_id: u16::from_str_radix(hex_id.trim(), 16).expect("group_id must be hex u16"),
                read: b.first().copied() == Some(b'R'),
                write: b.get(1).copied() == Some(b'W'),
                receive: b.get(2).copied() == Some(b'C'),
            }
        })
        .collect()
}

// ─── HSM static secret ────────────────────────────────────────────

/// Cached in OUT_DIR so incremental rebuilds keep the same key.
/// A `cargo clean` or new target dir triggers fresh generation.
fn load_or_generate_secret() -> StaticSecret {
    let path: PathBuf = Path::new(&env::var("OUT_DIR").unwrap()).join(".hsm_secret");

    if path.exists() {
        let bytes = fs::read(&path).expect("failed to read cached HSM secret");
        let arr: [u8; 32] = bytes.try_into().expect("cached HSM secret is not 32 bytes");
        return StaticSecret::from(arr);
    }

    let mut secret_bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut secret_bytes);
    fs::write(&path, &secret_bytes).expect("failed to persist HSM secret");

    StaticSecret::from(secret_bytes)
}

// ─── Cryptographic helpers ─────────────────────────────────────────

fn hash_pin(pin: &str) -> ([u8; 32], [u8; 16]) {
    let mut salt = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut salt);
    let mut key = [0u8; 32];
    pbkdf2_hmac::<Sha256>(pin.as_bytes(), &salt, 5, &mut key);
    (key, salt)
}

fn derive_aes_key(hsm_secret: &StaticSecret, peer_pub: &[u8; 32]) -> [u8; 16] {
    let shared = hsm_secret.diffie_hellman(&PublicKey::from(*peer_pub));
    let hk = Hkdf::<Sha256>::new(None, shared.as_bytes());
    let mut aes = [0u8; 16];
    hk.expand(b"aes-gcm key", &mut aes).expect("HKDF expand");
    aes
}

// ─── Formatting helpers ────────────────────────────────────────────

fn hex_inline(b: &[u8]) -> String {
    let h: Vec<_> = b.iter().map(|x| format!("0x{x:02X}")).collect();
    format!("[{}]", h.join(", "))
}

fn hex_block(b: &[u8], indent: usize) -> String {
    let pad = " ".repeat(indent);
    b.chunks(8)
        .map(|c| {
            let h: Vec<_> = c.iter().map(|x| format!("0x{x:02X}")).collect();
            format!("{pad}{},", h.join(", "))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn b64_key(v: &serde_json::Value) -> [u8; 32] {
    B64.decode(v.as_str().expect("expected JSON string"))
        .expect("base64 decode")
        .try_into()
        .expect("key must be exactly 32 bytes")
}

// ─── Code generation ───────────────────────────────────────────────

fn main() {
    let secrets_path = env::var("SECRETS_FILE").expect("env SECRETS_FILE required");
    let hsm_pin = env::var("HSM_PIN").expect("env HSM_PIN required");
    let perm_str = env::var("PERMISSIONS").expect("env PERMISSIONS required");

    for var in ["SECRETS_FILE", "HSM_PIN", "PERMISSIONS"] {
        println!("cargo:rerun-if-env-changed={var}");
    }
    println!("cargo:rerun-if-changed={secrets_path}");

    // ── Parse inputs ───────────────────────────────────────────────
    let json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(&secrets_path).expect("cannot read SECRETS_FILE"))
            .expect("invalid secrets JSON");

    let key_pairs = json["ecc_key_pairs"]
        .as_object()
        .expect("JSON missing `ecc_key_pairs` object");

    let hsm_secret = load_or_generate_secret();
    let hsm_public = PublicKey::from(&hsm_secret);

    let perms = parse_permissions(&perm_str);
    let (pin_hash, pin_salt) = hash_pin(&hsm_pin);

    // ── Open output file ───────────────────────────────────────────
    let dest: PathBuf =
        Path::new(&env::var("CARGO_MANIFEST_DIR").unwrap()).join("src/secrets_generated.rs");

    let mut f = fs::File::create(&dest).expect("cannot create secrets_generated.rs");

    macro_rules! w {
        ()              => { writeln!(f).unwrap() };
        ($($arg:tt)+)   => { writeln!(f, $($arg)+).unwrap() };
    }

    w!("// Auto-generated by build.rs — do not edit by hand");
    w!();

    w!(
        "pub const PIN_HASH: [u8; 32] = [\n{}\n];",
        hex_block(&pin_hash, 4)
    );
    w!();
    w!(
        "pub const PIN_SALT: [u8; 16] = [\n{}\n];",
        hex_block(&pin_salt, 4)
    );
    w!();
    w!("pub const NUM_PERMS: usize = {};", perms.len());
    w!();
    w!(
        "pub const HSM_PUBLIC_KEY: [u8; 32] = [\n{}\n];",
        hex_block(hsm_public.as_bytes(), 4)
    );
    w!();

    // ── RawGroupPermission ─────────────────────────────────────────
    w!("#[derive(Clone, Copy)]");
    w!("pub struct RawGroupPermission {{");
    w!("    pub group_id: u16,");
    w!("    pub read_perm: bool,");
    w!("    pub write_perm: bool,");
    w!("    pub receive_perm: bool,");
    w!("    pub read_encrypt_key: [u8; 16],");
    w!("    pub read_decrypt_key: [u8; 32],");
    w!("    pub write_signing_key_bytes: Option<[u8; 32]>,");
    w!("    pub write_verifying_key_bytes: [u8; 32],");
    w!("    pub receive_encrypt_key: [u8; 16],");
    w!("    pub receive_decrypt_key: [u8; 32],");
    w!("}}");
    w!();

    // ── RAW_PERMISSIONS array ──────────────────────────────────────
    w!("pub const RAW_PERMISSIONS: [RawGroupPermission; NUM_PERMS] = [");

    for p in &perms {
        let gid_str = p.group_id.to_string();
        let gk = key_pairs
            .get(&gid_str)
            .unwrap_or_else(|| panic!("no keys for group_id {gid_str} in secrets JSON"));

        let read_pub = b64_key(&gk["read"]["public"]);
        let write_pub = b64_key(&gk["write"]["public"]);
        let recv_pub = b64_key(&gk["receive"]["public"]);

        let read_priv: Option<[u8; 32]> = p.read.then(|| b64_key(&gk["read"]["private"]));
        let write_priv: Option<[u8; 32]> = p.write.then(|| b64_key(&gk["write"]["private"]));
        let recv_priv: Option<[u8; 32]> = p.receive.then(|| b64_key(&gk["receive"]["private"]));

        let read_aes = derive_aes_key(&hsm_secret, &read_pub);
        let recv_aes = derive_aes_key(&hsm_secret, &recv_pub);

        w!("    RawGroupPermission {{");
        w!("        group_id: {:#06x},", p.group_id);
        w!("        read_perm: {},", p.read);
        w!("        write_perm: {},", p.write);
        w!("        receive_perm: {},", p.receive);
        w!("        read_encrypt_key: {},", hex_inline(&read_aes));
        w!(
            "        read_decrypt_key: {},",
            hex_inline(&read_priv.unwrap_or([0; 32]))
        );
        match write_priv {
            Some(k) => w!("        write_signing_key_bytes: Some({}),", hex_inline(&k)),
            None => w!("        write_signing_key_bytes: None,"),
        }
        w!(
            "        write_verifying_key_bytes: {},",
            hex_inline(&write_pub)
        );
        w!("        receive_encrypt_key: {},", hex_inline(&recv_aes));
        w!(
            "        receive_decrypt_key: {},",
            hex_inline(&recv_priv.unwrap_or([0; 32]))
        );
        w!("    }},");
    }

    w!("];");
    w!();

    // ── init_permissions() ─────────────────────────────────────────
    w!("use crate::permission::{{");
    w!("    EncryptionKeyPair, GroupPermission, KeyPairSet, SignatureKeyPair,");
    w!("}};");
    w!("use ed25519_dalek::{{SigningKey, VerifyingKey}};");
    w!();
    w!("pub fn init_permissions() -> [GroupPermission; NUM_PERMS] {{");
    w!("    RAW_PERMISSIONS.map(|raw| GroupPermission {{");
    w!("        group_id: raw.group_id,");
    w!("        read_perm: raw.read_perm,");
    w!("        write_perm: raw.write_perm,");
    w!("        receive_perm: raw.receive_perm,");
    w!("        keys: KeyPairSet {{");
    w!("            read_keys: EncryptionKeyPair {{");
    w!("                encrypt_key: raw.read_encrypt_key,");
    w!("                decrypt_key: raw.read_decrypt_key,");
    w!("            }},");
    w!("            write_keys: SignatureKeyPair {{");
    w!("                signing_key: raw.write_signing_key_bytes");
    w!("                    .map(|b| SigningKey::from_bytes(&b)),");
    w!("                verifying_key: VerifyingKey::from_bytes(");
    w!("                    &raw.write_verifying_key_bytes,");
    w!("                )");
    w!("                .expect(\"bad verifying key in build-time data\"),");
    w!("            }},");
    w!("            receive_keys: EncryptionKeyPair {{");
    w!("                encrypt_key: raw.receive_encrypt_key,");
    w!("                decrypt_key: raw.receive_decrypt_key,");
    w!("            }},");
    w!("        }},");
    w!("    }})");
    w!("}}");
}
